# Generated by Django 4.2.1 on 2023-05-26 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0002_comment_created_date_comment_text"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="created_date",),
        migrations.RemoveField(model_name="comment", name="text",),
    ]
