# Generated by Django 4.2.1 on 2023-05-26 03:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0003_remove_comment_created_date_remove_comment_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="comment", name="text", field=models.TextField(null=True),
        ),
    ]
